name: Front CI
on:
  push:
    branches:
      - main
    path:
      - 'back/**'
  pull_request:
    branches:
      - main
    path:
      - 'back/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/front/.yarn
            ${{ github.workspace }}/front/.next/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/front/yarn.lock') }}
      - name: Restore and build
        working-directory: ./back
        run: |
          dotnet restore
          dotnet build KingCorp.WineCellar.Api