name: Front CI
on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: '22'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/front/.yarn
            ${{ github.workspace }}/front/.next/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/front/yarn.lock') }}
      - name: Install
        working-directory: ./front
        run: |
          yarn install --immutable
      - name: Build
        working-directory: ./front
        run: yarn build
